import os

PROJECT_ROOT = os.path.dirname(__file__)
ASSETS_DIR = os.path.join(PROJECT_ROOT, "assets")

# global boundaries
UPPER_BOUNDARY = 0
LOWER_BOUNDARY = 600
LEFT_BOUNDARY = 0
RIGHT_BOUNDARY = 800

# speed
PLAYER_SPEED = 5
ENEMY_SPEED = 0.1
PLAYER_BULLET_SPEED = 5
ENEMY_BULLET_SPEED = 0.1

# shooting
PLAYER_COOLDOWN = 5
ENEMY_COOLDOWN = 1
