import os

PROJECT_ROOT = os.path.dirname(__file__)
ASSETS_DIR = os.path.join(PROJECT_ROOT, "assets")

# global boundaries
UPPER_BOUNDARY = 0
LOWER_BOUNDARY = 600
LEFT_BOUNDARY = 0
RIGHT_BOUNDARY = 800

# TODO make these enums by level 
PLAYER_SPEED = 5
ENEMY_SPEED = 0.5
PLAYER_BULLET_SPEED = 5
ENEMY_BULLET_SPEED = 1

# TODO make these enums by level 
PLAYER_COOLDOWN = 0.3
ENEMY_COOLDOWN = 10
ENEMY_SHOOTING_PROBABILITY = 0.001
