import os

PROJECT_ROOT = os.path.dirname(__file__)
ASSETS_DIR = os.path.join(PROJECT_ROOT, "assets")

PLAYER_WIDTH = 40
PLAYER_HEIGHT = 40
BULLET_WIDTH = 10
BULLET_HEIGHT = 20

# global boundaries
UPPER_BOUNDARY = 0
LOWER_BOUNDARY = 600
LEFT_BOUNDARY = 0
RIGHT_BOUNDARY = 800

# make these enumerations (levels)
PLAYER_SPEED = 5
ENEMY_SPEED = 1
PLAYER_BULLET_SPEED = 5
ENEMY_BULLET_SPEED = 3

PLAYER_MAX_HITS = 3
ENEMY_MAX_HITS = 1

PLAYER_COOLDOWN = 0.3
ENEMY_COOLDOWN = 30
ENEMY_SHOOTING_PROBABILITY = 0.0008

ENEMY_COUNT_COLS = 4
ENEMY_ROWS = 2
